#! /bin/bash
#
# Postwhite - Automatic Postcreen Whitelist Generator
#
# By Steve Jenkins (http://stevejenkins.com/)
  version=1.13
# Last updated: 28 Nov 2015
#
# Usage: place entire postwhite directory in /usr/local/bin then 
# run ./postwhite
#
# Requires spf-tools (https://github.com/jsarenik/spf-tools)
# Requires ipcalc (http://jodies.de/ipcalc)

# Thanks to Mike Miller (mmiller@mgm51.com) for gwhitelist.sh script
# Thanks to Jose Borges Ferreira for IPv4 normalization help

# USER-DEFINABLE OPTIONS

# spf-tools location (REQUIRED)
spftoolspath=/usr/local/bin/spf-tools

# ipcalc location (REQUIRED)
ipcalc=/usr/local/bin/postwhite/ipcalc/ipcalc

# Do this to invalid IPv4 addresses and CIDRs (keep / strip / fix)
badip4=strip

# Paths
postfixpath=/etc/postfix
postfixbinarypath=/usr/sbin
whitelist=postscreen_spf_whitelist.cidr

# Toggle senders you want to include below

# Webmail Providers
aol=yes
google=yes
gmx=yes
inbox=yes
mac=yes
mail=yes
microsoft=yes
zoho=yes

#Social Networks
facebook=yes
instagram=yes
linkedin=yes
pinterest=yes
reddit=yes
tumblr=yes
twitter=yes

# Ecommerce
amazon=no
craigslist=yes
ebay=yes

# Bulk Senders
constantcontact=yes
exacttarget=yes
icontact=yes
mailchimp=yes
sendgrid=yes

# Misc
zendesk=yes

# Reload Postfix Automatically when done?
reloadpostfix=yes

# NO NEED TO EDIT PAST THIS LINE

# abort on any error
set -e

# Create temporary files
tmpBase=$(basename "$0")
tmp1=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
tmp2=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
tmp3=$(mktemp -q /tmp/"${tmpBase}".XXXXXX)
	if [ $? -ne 0 ]; then
		echo "$0: Can't create temp file, exiting..."
		exit 1
	fi

# Create IPv4 normalization function

ip2int() {
    local a b c d
    { IFS=. read a b c d; } <<< $1
    echo $(((((((a << 8) | b) << 8) | c) << 8) | d))
}

int2ip() {
    local ui32=$1; shift
    local ip n
    for n in 1 2 3 4; do
        ip=$((ui32 & 0xff))${ip:+.}$ip
        ui32=$((ui32 >> 8))
    done
    echo $ip
}

network() {
    local ip netmask;
    { IFS="/" read ip netmask; } <<< $1
    local addr=$(ip2int $ip);
    local mask=$((0xffffffff << (32 -$netmask)));
    echo $(int2ip $((addr & mask)))/$netmask
}

function normalize_ipv4() {
	# split by ":"
	local array=(${ip/:/ });
	if [ "x${array[0]}" = "xip4" ] ; then
		# check if is a CIDR
		if [[ ${array[1]} == *"/"32 ]] ; then
			IP=${array[1]}
		elif [[ ${array[1]} == *"/"* ]] ; then
			IP=$(network ${array[1]});
		else
			IP=${array[1]}
		fi
	else
		IP=${array[1]}
	fi
	echo "$IP"
}

# Recursively query selected mailers' SPF records
if [ "$google" == "yes" ]; then
	${spftoolspath}/despf.sh google.com >> "${tmp1}"
fi

if [ "$microsoft" == "yes" ]; then
	${spftoolspath}/despf.sh outlook.com >> "${tmp1}"
	${spftoolspath}/despf.sh hotmail.com >> "${tmp1}"
fi

if [ "$aol" == "yes" ]; then
	${spftoolspath}/despf.sh aol.com >> "${tmp1}"
fi

if [ "$gmx" == "yes" ]; then
	${spftoolspath}/despf.sh gmx.com >> "${tmp1}"
fi

if [ "$mac" == "yes" ]; then
	${spftoolspath}/despf.sh icloud.com >> "${tmp1}"
fi

if [ "$mail" == "yes" ]; then
	${spftoolspath}/despf.sh mail.com >> "${tmp1}"
fi

if [ "$inbox" == "yes" ]; then
	${spftoolspath}/despf.sh inbox.com >> "${tmp1}"
fi

if [ "$zoho" == "yes" ]; then
	${spftoolspath}/despf.sh zoho.com >> "${tmp1}"
fi

if [ "$facebook" == "yes" ]; then
	${spftoolspath}/despf.sh facebookmail.com >> "${tmp1}"
fi

if [ "$twitter" == "yes" ]; then
	${spftoolspath}/despf.sh twitter.com >> "${tmp1}"
fi

if [ "$pinterest" == "yes" ]; then
	${spftoolspath}/despf.sh pinterest.com >> "${tmp1}"
fi

if [ "$instagram" == "yes" ]; then
	${spftoolspath}/despf.sh instagram.com >> "${tmp1}"
fi

if [ "$tumblr" == "yes" ]; then
	${spftoolspath}/despf.sh tumblr.com >> "${tmp1}"
fi

if [ "$reddit" == "yes" ]; then
	${spftoolspath}/despf.sh reddit.com >> "${tmp1}"
fi

if [ "$linkedin" == "yes" ]; then
	${spftoolspath}/despf.sh linkedin.com >> "${tmp1}"
fi

if [ "$craigslist" == "yes" ]; then
	${spftoolspath}/despf.sh craigslist.org >> "${tmp1}"
fi

if [ "$amazon" == "yes" ]; then
	${spftoolspath}/despf.sh amazon.com >> "${tmp1}"
fi

if [ "$ebay" == "yes" ]; then
	${spftoolspath}/despf.sh s._spf.ebay.com >> "${tmp1}"
	${spftoolspath}/despf.sh c._spf.ebay.com >> "${tmp1}"
	${spftoolspath}/despf.sh p._spf.ebay.com >> "${tmp1}"
fi

if [ "$sendgrid" == "yes" ]; then
	${spftoolspath}/despf.sh sendgrid.com >> "${tmp1}"
	${spftoolspath}/despf.sh sendgrid.net >> "${tmp1}"
fi

if [ "$mailchimp" == "yes" ]; then
	${spftoolspath}/despf.sh mailchimp.com >> "${tmp1}"
fi

if [ "$exacttarget" == "yes" ]; then
	${spftoolspath}/despf.sh exacttarget.com >> "${tmp1}"
fi

if [ "$constantcontact" == "yes" ]; then
	${spftoolspath}/despf.sh constantcontact.com >> "${tmp1}"
fi

if [ "$icontact" == "yes" ]; then
	${spftoolspath}/despf.sh icontact.com >> "${tmp1}"
fi


if [ "$zendesk" == "yes" ]; then
	${spftoolspath}/despf.sh zendesk.com >> "${tmp1}"
fi

# Check for invalid IPv4 addresses/CIDRs, then format the whitelist
if [ "$badip4" == "fix" ] ; then
	for ip in $(cat  "${tmp1}") ; do
		ip=$(normalize_ipv4  "$ip");
		if [ -n "$ip" ] ; then
			echo -ne "$ip\tpermit\n"
		fi
	done >> "${tmp2}"
elif [ "$badip4" == "strip" ] ; then
	for ip in $(cat "${tmp1}") ; do
		iptype=$( echo "$ip" | cut -d\: -f1 )
		origip=$( echo "$ip" | cut -d\: -f2 )
		ip=$(normalize_ipv4 "$ip");
		if [ "$origip" == "$ip" ] ; then
			echo -ne "$ip\tpermit\n"
		elif [ "$iptype" == "ip6" ] ; then
			echo -ne "$ip\tpermit\n"
		fi
		done >> "${tmp2}"
elif [ "$badip4" == "keep" ] ; then

	printf "%s\n" | grep "^ip" "${tmp1}" | cut -c5- | sed s/$/'	permit'/ > "${tmp2}"
fi

# Sort and unique the final list and write finalized whitelist to Postfix directory
sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n -u "${tmp2}" > "${tmp3}"
numentries=$(cat "${tmp3}" | wc -l)
echo -e "# Generated by Postwhite v$version on $(date)\n# https://github.com/stevejenkins/postwhite/\n# $numentries total entries" > "${postfixpath}"/"${whitelist}"
cat "${tmp3}" >> "${postfixpath}"/"${whitelist}"

# Remove temp files
test -e "${tmp1}" && rm "${tmp1}"
test -e "${tmp2}" && rm "${tmp2}"
test -e "${tmp3}" && rm "${tmp3}"

# Reload Postfix to pick up changes in whitelist
if [ "$reloadpostfix" == "yes" ]; then
	${postfixbinarypath}/postfix reload
fi

exit
